spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        use_sql_comments: true;
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    password: asdf****
    username: root
    url: jdbc:mysql://localhost:3306/file-apis?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
  servlet:
    multipart:
      max-file-size: 1024MB
      enabled: true
      max-request-size: 1024MB
      file-size-threshold: 2KB
  jackson:
    deserialization:
      fail-on-unknown-properties: true
server:
  servlet:
    encoding:
      force-response: true
      charset: UTF-8
file:
  public-space-dir: ${user.home}/Download/public
  protect-space-dir: ${user.home}/Download/protect
  download-public-path: /public-file-download/
  upload-dir: ${user.home}/Download
  download-path: /file-download/

#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace;

decorator:
  datasource:
    p6spy:
      enable-logging: true
